# Generated by Django 3.2.11 on 2022-01-18 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_ip_adress', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=255, null=True)),
                ('link1', models.CharField(max_length=510)),
                ('link2', models.CharField(max_length=510)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('test_views', models.IntegerField(blank=True, default=0, null=True)),
                ('js_views', models.IntegerField(blank=True, default=0, null=True)),
                ('link_clicked', models.IntegerField(blank=True, default=0, null=True)),
                ('sygnal_link1', models.IntegerField(default=0)),
                ('sygnal_link2', models.IntegerField(default=0)),
                ('sygnal_wynik', models.IntegerField(default=0)),
                ('wyswietlenia_link1', models.IntegerField(default=1)),
                ('wyswietlenia_link2', models.IntegerField(default=1)),
                ('wyswietlenia_wynik', models.IntegerField(default=1)),
                ('suma_wyswietlenia_linkow', models.IntegerField(default=1)),
                ('ukonczenie_celu1', models.IntegerField(default=0)),
                ('ukonczenie_celu2', models.IntegerField(default=0)),
                ('suma_ukonczenia_celow', models.IntegerField(default=0)),
                ('konwersja1', models.FloatField(blank=True, default=0, null=True)),
                ('konwersja2', models.FloatField(blank=True, default=0, null=True)),
                ('suma_konwersji', models.FloatField(default=0)),
                ('sygnal_konwersja1', models.IntegerField(default=0)),
                ('sygnal_konwersja2', models.IntegerField(default=0)),
                ('button_like_clicked', models.ManyToManyField(blank=True, related_name='mytest_button_like_clicked', to=settings.AUTH_USER_MODEL)),
                ('unique_views', models.ManyToManyField(blank=True, related_name='mytest_unique_post_views', to='mojetesty.IpModels')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KonwersjaDzienna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wersja', models.IntegerField(default=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('datatestowa', models.DateTimeField(blank=True, null=True)),
                ('idtestu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mojetesty.mytests')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dzienne konwersje',
            },
        ),
    ]
